name: CI - Docker Build & Test

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build ./app -t it-dashboard:latest

      - name: Test container startup
        run: |
          docker run -d -p 5000:5000 --name test-app it-dashboard:latest
          sleep 5
          docker logs test-app
          docker stop test-app
